# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ccusage = nodeEnv.buildNodePackage {
    name = "ccusage";
    packageName = "ccusage";
    version = "18.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-18.0.5.tgz";
      sha512 = "bnZrVbGm5h7hIIOH3FZFaDxKgJLLHhWDWIv7/9M6/O373YM6RAwsG9hxZXA1ep+C2ISiNEX6MYVoXgkoSuFf9Q==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Usage analysis tool for Claude Code";
      homepage = "https://github.com/ryoppippi/ccusage#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
